apiVersion: v1
kind: Namespace
metadata:
  name: readyhat-gitops-demo
  annotations:
    openshift.io/description: An application scoped instance of ArgoCD.
    openshift.io/display-name: Red Hat GitOps Demo