apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readyhat-gitops-demo
  namespace: gitops-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
  # can be different namespace but need to match one that is created by DevOps engineer in OCP UI
    namespace: gitops-demo
    server: 'https://kubernetes.default.svc'
  # project: readyhat-gifstream
  project: default
  source:
    path: deploy
    # repoURL: 'https://github.com/readyhat/gif2stream.git'
    repoURL: 'https://github.com/readyhat/gitops-demo-cicd.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
