#
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: readyhat-gitops-demo

commonLabels:
  app: readyhat-gitops-demo
  
resources:
- deployment.yaml
- service.yaml
- route.yaml