apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: readyhat-gifstream
  namespace: readyhat-gifstream
spec:
  description: 'The GifStream project. '
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'